version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install EVA package with test dependencies
          command: |
            python -m venv eva_dev_env
            . eva_dev_env/bin/activate
            pip install --upgrade pip
            pip install ".[dev]"

      - run:
          name: Generate Parser Files
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo -E apt install -y openjdk-8-jdk openjdk-8-jre
            sh script/antlr4/generate_parser.sh

      - run:
          name: Test
          command: |
            . eva_dev_env/bin/activate
            sh script/test/test.sh
            coveralls

workflows:
  main:
    jobs:
      - build-and-test
